# Generated by Django 5.1.5 on 2025-01-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='text',
            field=models.TextField(default='ali'),
        ),
    ]
