# Generated by Django 5.1.5 on 2025-01-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='text',
        ),
    ]
